name: Post Instagram Reel Daily

on:
  schedule:
    - cron: "0 12 * * *"   # runs daily at 14:00 Italy (12:00 UTC)

  workflow_dispatch: {}

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post reel
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          python post_reels.py \
            --video-url "https://github.com/osamaPY/chakchabani/raw/refs/heads/main/chakchabani.mp4" \
            --caption "chakchabani day $(date -u +'%Y-%m-%d')"
